services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=["http://localhost:3000"]
    env_file: ".env"
    command: uv run uvicorn app.main:app --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:8000
    env_file: ".env"
    command: npm run dev
