services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./pyproject.toml:/pyproject.toml
      - ./uv.lock:/uv.lock
    environment:
      - ENVIRONMENT=development
    env_file: ".env"
    command: uv run python run_agent.py --quick

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:8000
    env_file: ".env"
    command: npm run dev
