services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=["http://localhost:3000"]
    env_file: ".env"
    command: uv run uvicorn app.main:app --host=0.0.0.0 --port=8000
